# Generated by Django 5.1.7 on 2025-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_comment_updated_at_alter_comment_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=5000),
        ),
    ]
